name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *" # todo dia às 00:00 BR
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Adicionado -sSL para seguir redirecionamentos e -o para salvar corretamente
      # Trocado o ' por %27 no custom_title
      - name: Generate GitHub Stats SVG
        run: |
          curl -sSL "https://github-readme-stats.vercel.app/api?username=FelipeAkryghti&custom_title=Felipe%20Akryghti%27s%20GitHub%20Stats&bg_color=0a111a&title_color=61bdf2&icon_color=61bdf2&text_color=ffffff&show_icons=true&hide_border=true&count_private=true" -o github-metrics.svg

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub stats SVG layout"
          file_pattern: "github-metrics.svg"
